x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.3.2}
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: 'fernet_key'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__LOGGING__REMOTE_LOGGING: 'false'              
    AIRFLOW__WEBSERVER__SECRET_KEY: 'j2P5nWc7oYp8vCk3qLx9tZg1rD4mH6sB1fT2uV3wX5yZ7a'  
    PYTHONPATH: /opt/airflow:/opt/airflow/dags:/opt/airflow/plugins:/opt/airflow/src
    _PIP_ADDITIONAL_REQUIREMENTS: "pytest"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
    - ./logs:/opt/airflow/logs
    - ./tests:/opt/airflow/tests                              
  user: "${AIRFLOW_UID:-50000}:0"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        set -e
        airflow db init
        airflow users create \
          --username admin --password admin \
          --firstname admin --lastname admin \
          --role Admin --email admin@example.com || true
    depends_on:
      - postgres

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - postgres
      - airflow-init

  airflow-cli:
    <<: *airflow-common
    entrypoint: /bin/bash
    command: ["-lc", "airflow"]
    depends_on:
      - postgres
      - airflow-init

volumes:
  postgres-db-volume:
